# Generated by Django 5.0.6 on 2026-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('base', 'Base'), ('sauce', 'Sauce'), ('cheese', 'Cheese'), ('vegetable', 'Vegetable')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_c_name_b82d17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ingredients_text', models.TextField(blank=True, help_text='Comma separated display text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_096500_idx'), models.Index(fields=['is_available'], name='inventory_p_is_avai_ac4fc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PizzaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_5b3fb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_s_name_a7b819_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_v_name_6efea3_idx')],
            },
        ),
    ]
