# Generated by Django 5.0.6 on 2026-08-14 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['-is_featured', '-rating']},
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('burger', 'Burger'), ('sides', 'Sides'), ('drinks', 'Drinks'), ('desserts', 'Desserts')], default='pizza', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='delivery_time',
            field=models.CharField(default='25-30 min', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount percentage'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='pizza',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['category'], name='inventory_p_categor_5be99b_idx'),
        ),
        migrations.AddField(
            model_name='rating',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inventory.pizza'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('pizza', 'user')},
        ),
    ]
