# Generated by Django 5.0.6 on 2026-08-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rating_alter_pizza_options_pizza_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (takes precedence over ImageField)', null=True),
        ),
    ]
